
- name: Updating
  shell: apt update

- name: Installing Essentials Tools
  script: scripts/install-essentials.sh

- name: Install bettercap
  apt:
    name: bettercap
    state: present

- name: Install tree
  apt:
    name: tree
    state: present

- name: Update the database
  shell: updatedb

